# Data only to upload to production
- type: web
  name: nextjs-static
  runtime: static
  buildCommand: yarn; yarn build
  staticPublishPath: out
  pullRequestPreviewsEnabled: true
envVars:
- key: NODE_ENV
  value: production